twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        domain: '%domain%'
        mobile: '%mobile%'
        site_name: '%site_name%'
        home_title: '%home_title%'
        site_desc: '%site_desc%'
        site_key: '%site_key%'
        site_logo: '%site_logo%'
        facebook_app_id: '%facebook_app_id%'
        static_url: '%static_url%%static_folder%'