# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    listener.request:
        class: App\EventListener\RequestListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
#    app.twig_extension:
#        class: App\Service\AppExtension
#        arguments: ['@service_container']
#        public: false
#        tags:
#            - { name: twig.extension }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\Category:
        class: App\Service\Category
        arguments: ['@request_stack', '@doctrine', '%cache_config%']
        public: true
    App\Service\Images:
        class: App\Service\Images
        arguments: ['%media_url%']
        public: true
    App\Service\DataExchange:
        class: App\Service\DataExchange
        arguments: ['@router', '%domain%', '@App\Service\Images', '@App\Service\Category']
#            $router: '@router'
#            $domain: '%domain%'
#            $imageService: '@App\Service\Images'
        autowire: true
        public: true
    App\Service\ElasticSearch:
        class: App\Service\ElasticSearch
        arguments: ['%elasticsearch_url%', 30]
        public: true
    App\Service\Sitemap:
            class: App\Service\Sitemap
            arguments: ['@router', '%domain%', '%site_name%', '@App\Service\Images']
    App\Service\CryptUtils:
        class: App\Service\CryptUtils
        arguments: ['%crypt%']