search_posts:
    path: /search
    defaults: {_controller: Mobile\Controller\Search\IndexController::searchAction}
ajax_get_search_posts:
    path: /ajax/search-post.json
    defaults: {_controller: Mobile\Controller\Search\AjaxController::getSearchPostAction}