ajax_post_home_stream:
    path:   /ajax/home-stream
    defaults: {_controller: App\Controller\AjaxController::getHomeStreamPosts}
    options:
        utf8: true
ajax_cate_stream:
    path:     /ajax/cate-stream
    defaults: {_controller: App\Controller\Category\AjaxController::getCateStreamPosts}
ajax_tag_stream:
    path:     /ajax/tag
    defaults: {_controller: App\Controller\Tag\AjaxController::getTagStreamPosts}

